apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  namespace: notes-app-ns
spec:
  type: NodePort
  selector:
    app: notes-app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30007
